###################
# Builder stage   #
###################
FROM golang:1.21-alpine AS builder

ARG VERSION

WORKDIR /src

# Grab deps first for better cache
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .
RUN cd cmd && go build -ldflags="-X 'github.com/NaeuralEdgeProtocol/ratio1-backend/config.BackendVersion=${VERSION}'" -o backend


###################
# Runtime image   #
###################
FROM gcr.io/distroless/static:nonroot
ARG VERSION

LABEL org.opencontainers.image.version=$VERSION
COPY --from=builder /app/backend /ratio1-backend
COPY templates/html /templates/html
COPY config          /config

USER nonroot
ENTRYPOINT ["/backend"]

