###################
# Builder stage   #
###################
FROM golang:1.21-alpine AS builder

ARG VERSION

WORKDIR /src

# Grab deps first for better cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest and build
COPY . .
RUN CGO_ENABLED=0 \
    go build -ldflags "-s -w \
      -X github.com/NaeuralEdgeProtocol/ratio1-backend/config.BackendVersion=${VERSION}" \
    -o /app/ratio1-backend ./cmd


###################
# Runtime image   #
###################
FROM gcr.io/distroless/static:nonroot
ARG VERSION

LABEL org.opencontainers.image.version=$VERSION
COPY --from=builder /app/ratio1-backend /ratio1-backend
COPY templates/html /templates/html
COPY config          /config

USER nonroot
ENTRYPOINT ["/ratio1-backend"]

