name: Build and Push Container Image

on:
    push:
        branches: [main]
    # also allow manual runs
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: docker/setup-qemu-action@v3
            - uses: docker/setup-buildx-action@v3

            - name: Docker Hub login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Generate Semantic Version
              id: version
              uses: PaulHatch/semantic-version@v5.4.0
              with:
                  tag_prefix: "v"
                  major_pattern: "(MAJOR)"
                  minor_pattern: "(feat|feature)"
                  version_format: "${major}.${minor}.${patch}"

            - name: Build & Push Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile_allnet
                  push: true
                  platforms: linux/amd64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args: |
                      VERSION=${{ steps.version.outputs.version }}
                  tags: |
                      vitaliitoderian/ratio1_backend

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.version.outputs.version_tag }}
                  name: v${{ steps.version.outputs.version }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
